let a=25;
let b=20;
let c=a+b;
let d=a-b;
let e=a*b;
let f=a/b;
alert("La suma es:"+c+"\n");
document.write("La suma es:"+c);
alert("La resta es:"+d);
document.write("La resta es:"+d);
alert("El producto es:"+e);
document.write("El producto es:"+e);
alert("La division es:"+f);
document.write("La division es:"+f);